Embrapa Wine Grape Instance Segmentation Dataset - Embrapa WGISD

* Motivation for Dataset Creation

** Why was the dataset created?

Embrapa WGISD (/Wine Grape Instance Segmentation Dataset/) was created
to provide images and annotation to study /object detection and
instance segmentation/ in image-based monitoring and field robotics
for viticulture. It provides instances from five different grape
varieties taken on field. These instances shows variance in grape
pose, illumination and focus, including genetic and phenological
variations as shape, color and compactness. 

** What (other) tasks could the dataset be used for?

Possible uses include relaxations of the instance segmentation
problem: classification (Is a grape in the image?), semantic
segmentation (What are the "grape pixels" in the image?), object
detection (Where are the grapes in the image?). The WGISD can be also
in grape variety identification.

** Has the dataset been used for any tasks already?

** Who funded the creation of the dataset?

The building of the WGISD dataset was supported by the Embrapa SEG
Project 01.14.09.001.05.04, /Image-based metrology for Precision
Agriculture and Phenotyping/, and the CNPq PIBIC Program.

* Dataset Composition

** What are the instances?

Each instance consists in a 2048 x 1365 RGB image image and an
annotation describing grape bunches locations as bounding boxes. A 
subset of the instances also contains binary masks identifying the
pixels belonging to each grape bunch. Each image presents at least one
grape bunch. Some grape bunches can appear far at the background and
should be ignored.

** Are relationships between instances made explicit in the data?

** How many instances of each type are there?

300 images, 1898 bunches, 5 varieties

| Code  | Variety              |       Date | N. Images | N. bunches |
|-------+----------------------+------------+-----------+------------|
| CDY   | /Chardonnay/         | 2018-04-27 |        65 |        273 |
| CFR   | /Cabernet Franc/     | 2018-04-27 |        65 |        467 |
| CSV   | /Cabernet Sauvignon/ | 2018-04-27 |        57 |        296 |
| SVB   | /Sauvignon Blanc/    | 2018-04-27 |        65 |        597 |
| SYH   | /Syrah/              | 2017-04-27 |        48 |        265 |
|-------+----------------------+------------+-----------+------------|
| Total |                      |            |       300 |       1898 |

** What data does each instance consist of?

** Is everything included or does the data rely on external resources?

** Are there recommended data splits or evaluation measures?

** What experiments were initially run on this dataset?

** Any other comments?

* Data Collection Process

** How was the data collected?

** Who was involved in the data collection process?

** How was the data associated with each instance acquired?

** Does the dataset contain all possible instances?

** If the dataset is a sample, then what is the population?

** Is there information missing from the dataset and why?

** Are there any known errors, sources of noise, or redundancies in the data?

** Any other comments?

* Data Preprocessing

* Datset Distribution

* Dataset Maintenance

* Legal & Ethical Considerations

